version: "3.8"

services:
  vue-academy-module4:
    container_name: vue-academy-module4
    build:
      context: ../module4/server
      dockerfile: ../../docker/Dockerfile
      args:
        GID: ${GID}
        UID: ${UID}
        PORT: ${PORT}
        NODE_ENV: ${NODE_ENV}
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ../module4/server:/var/www/backend
    networks:
      vue-academy:
        ipv4_address: 172.24.210.2

networks:
  vue-academy:
    external: true
